name: prayer_guard_desktop
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  system_tray: ^2.0.3
  bitsdojo_window: ^0.1.5
  intl: ^0.18.1
  timezone: ^0.9.2
  salat: ^1.0.4
  geolocator_windows: ^0.1.2
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.1
  flutter_phoenix: ^1.1.1
  launch_at_startup: ^0.2.2
  package_info_plus: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.16.4

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-Bold.ttf

msix_config:
  display_name: Prayer Guard
  publisher_display_name: Muslims code
  msix_version: 1.0.0.3
  logo_path: C:\coding\haqq\prayer_guard\prayer_guard_desktop\assets\prayer_guard_logo.png
